// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'gcloud.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> greet() => RustLib.instance.api.crateApiGreet();

Future<bool> checkGcloudInstalled() =>
    RustLib.instance.api.crateApiCheckGcloudInstalled();

Future<bool> checkGcloudAuth() =>
    RustLib.instance.api.crateApiCheckGcloudAuth();

Future<void> gcloudLogin() => RustLib.instance.api.crateApiGcloudLogin();

Future<List<GcpProject>> listProjects() =>
    RustLib.instance.api.crateApiListProjects();

Future<List<GcpInstance>> listInstances({required String projectId}) =>
    RustLib.instance.api.crateApiListInstances(projectId: projectId);

Future<int> startConnection({
  required String projectId,
  required String zone,
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiStartConnection(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  remotePort: remotePort,
);

Future<void> stopConnection({required String instanceName}) =>
    RustLib.instance.api.crateApiStopConnection(instanceName: instanceName);

Future<void> launchRdp({required int port, required String instanceName}) =>
    RustLib.instance.api.crateApiLaunchRdp(
      port: port,
      instanceName: instanceName,
    );
