// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'gcloud.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'remmina.dart';
import 'sftp.dart';

Future<String> greet() => RustLib.instance.api.crateApiGreet();

Future<bool> checkGcloudInstalled() =>
    RustLib.instance.api.crateApiCheckGcloudInstalled();

Future<bool> checkGcloudAuth() =>
    RustLib.instance.api.crateApiCheckGcloudAuth();

Future<void> gcloudLogin() => RustLib.instance.api.crateApiGcloudLogin();

Future<void> gcloudLogout() => RustLib.instance.api.crateApiGcloudLogout();

Future<List<GcpProject>> listProjects() =>
    RustLib.instance.api.crateApiListProjects();

Future<List<GcpInstance>> listInstances({required String projectId}) =>
    RustLib.instance.api.crateApiListInstances(projectId: projectId);

Future<int> startConnection({
  required String projectId,
  required String zone,
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiStartConnection(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  remotePort: remotePort,
);

Future<void> stopConnection({
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiStopConnection(
  instanceName: instanceName,
  remotePort: remotePort,
);

Future<bool> checkConnectionHealth({
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiCheckConnectionHealth(
  instanceName: instanceName,
  remotePort: remotePort,
);

Future<void> launchRdp({
  required int port,
  required String instanceName,
  required RdpSettings settings,
}) => RustLib.instance.api.crateApiLaunchRdp(
  port: port,
  instanceName: instanceName,
  settings: settings,
);

Future<void> launchSsh({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiLaunchSsh(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> launchSftp({required int port, String? username}) =>
    RustLib.instance.api.crateApiLaunchSftp(port: port, username: username);

Future<void> initLoggingSystem() =>
    RustLib.instance.api.crateApiInitLoggingSystem();

Future<String> exportLogsToFile() =>
    RustLib.instance.api.crateApiExportLogsToFile();

Future<String> getLogFilePath() =>
    RustLib.instance.api.crateApiGetLogFilePath();

Future<List<RemoteFileEntry>> sftpListDir({
  required String host,
  required int port,
  required String username,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpListDir(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
);

Future<BigInt> sftpDownload({
  required String host,
  required int port,
  required String username,
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSftpDownload(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
  localPath: localPath,
);

Future<BigInt> sftpUpload({
  required String host,
  required int port,
  required String username,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpUpload(
  host: host,
  port: port,
  username: username,
  localPath: localPath,
  remotePath: remotePath,
);

Future<void> sftpMkdir({
  required String host,
  required int port,
  required String username,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpMkdir(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
);

Future<void> sftpDelete({
  required String host,
  required int port,
  required String username,
  required String remotePath,
  required bool isDirectory,
}) => RustLib.instance.api.crateApiSftpDelete(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
  isDirectory: isDirectory,
);

Future<String> getUsername() => RustLib.instance.api.crateApiGetUsername();

Future<void> startInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiStartInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> stopInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiStopInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> resetInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiResetInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);
