// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GcpInstance {
  final String name;
  final String status;
  final String zone;

  const GcpInstance({
    required this.name,
    required this.status,
    required this.zone,
  });

  @override
  int get hashCode => name.hashCode ^ status.hashCode ^ zone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpInstance &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          zone == other.zone;
}

class GcpProject {
  final String projectId;
  final String? name;

  const GcpProject({required this.projectId, this.name});

  @override
  int get hashCode => projectId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpProject &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          name == other.name;
}
