// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Represents a remote file or directory entry
class RemoteFileEntry {
  final String name;
  final String path;
  final bool isDirectory;
  final BigInt size;
  final PlatformInt64? modified;
  final int? permissions;

  const RemoteFileEntry({
    required this.name,
    required this.path,
    required this.isDirectory,
    required this.size,
    this.modified,
    this.permissions,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDirectory.hashCode ^
      size.hashCode ^
      modified.hashCode ^
      permissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDirectory == other.isDirectory &&
          size == other.size &&
          modified == other.modified &&
          permissions == other.permissions;
}
